"""Phase 6: Report — Export summary tables and boilerplate for the paper.

Supports Markdown and LaTeX output formats.
"""
from pathlib import Path
from typing import Any


def build_summary_table(solver_result: dict[str, Any] | None,
                        validation_result: dict[str, Any] | None) -> str:
    """Build a markdown summary table from solver + validation results."""
    lines = ["# Model Results Summary\n", "| Metric | Value |", "|--------|-------|"]
    if solver_result:
        for key in ("r2", "adj_r2", "rmse", "converged"):
            if key in solver_result:
                val = str(solver_result[key])
                val = val.split(".")[0] if val == "True" or val == "False" else val
                lines.append(f"| {key} | {solver_result[key]} |")
    if validation_result:
        ra = validation_result.get("residual_analysis", {})
        for key in ("mean_residual", "std_residual", "min_residual", "max_residual"):
            if key in ra and ra[key] is not None:
                lines.append(f"| {key} | {ra[key]:.4f} |")
    return "\n".join(lines)


def build_latex_table(solver_result: dict[str, Any] | None,
                      validation_result: dict[str, Any] | None) -> str:
    """Build a LaTeX table from solver + validation results."""
    rows = []
    # Collect rows
    if solver_result:
        for key in ("r2", "adj_r2", "rmse", "converged"):
            if key in solver_result:
                v = solver_result[key]
                if isinstance(v, float):
                    val = f"{v:.4f}"
                else:
                    val = str(v)
                rows.append((key.replace("_", "\\_"), val))
    if validation_result:
        ra = validation_result.get("residual_analysis", {})
        for key in ("mean_residual", "std_residual", "min_residual", "max_residual"):
            if key in ra and ra[key] is not None:
                rows.append((key.replace("_", "\\_"), f"{ra[key]:.4f}"))

    n = len(rows)
    lines = [
        "\\begin{table}[h]",
        "\\centering",
        "\\begin{tabular}{lr}",
        "\\hline",
        "\\textbf{Metric} & \\textbf{Value} \\\\",
        "\\hline",
    ]
    for name, val in rows:
        lines.append(f"{name} & {val} \\\\")
    lines += [
        "\\hline",
        "\\end{tabular}",
        "\\caption{Model Results Summary}",
        "\\label{tab:model_results}",
        "\\end{table}",
    ]
    return "\n".join(lines)


def export_markdown_report(solver_result: dict[str, Any] | None,
                           validation_result: dict[str, Any] | None,
                           viz_result: dict[str, Any] | None,
                           output_path: str | Path) -> str:
    """Export a complete markdown report with all results."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    sections = ["# Contest Report\n"]
    sections.append(build_summary_table(solver_result, validation_result) + "\n")
    if viz_result and viz_result.get("figures"):
        sections.append("## Figures\n")
        for name, figpath in viz_result["figures"].items():
            sections.append(f"- {name}: `{figpath}`\n")
    sections.append("\n---\n*Generated by math-modeling-starter (FDE mode)*\n")
    report = "\n".join(sections)
    path.write_text(report, encoding="utf-8")
    return str(path)


def export_latex_report(solver_result: dict[str, Any] | None,
                        validation_result: dict[str, Any] | None,
                        viz_result: dict[str, Any] | None,
                        output_path: str | Path) -> str:
    """Export a LaTeX report with table and figure includes."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    sections = [
        "% --- Auto-generated LaTeX Report ---",
        "\\documentclass{article}",
        "\\usepackage{booktabs}",
        "\\usepackage{graphicx}",
        "\\usepackage[margin=1in]{geometry}",
        "\\begin{document}",
        "",
        "\\title{Contest Report}",
        "\\maketitle",
        "",
    ]
    sections.append(build_latex_table(solver_result, validation_result))
    sections.append("")

    if viz_result and viz_result.get("figures"):
        sections.append("\\section*{Figures}\n")
        for name, figpath in viz_result["figures"].items():
            rel = figpath.replace("\\", "/")
            sections.append(
                f"\\begin{{figure}}[h]\n"
                f"\\centering\n"
                f"\\includegraphics[width=0.8\\textwidth]{{{rel}}}\n"
                f"\\caption{{{name.replace('_', ' ').title()}}}\n"
                f"\\end{{figure}}\n"
            )

    sections += ["", "\\end{document}"]

    report = "\n".join(sections)
    path.write_text(report, encoding="utf-8")
    return str(path)


def run(solver_result: dict | None = None,
        validation_result: dict | None = None,
        viz_result: dict | None = None,
        config: dict | None = None) -> dict[str, Any]:
    """Execute Phase 6: generate report (Markdown and/or LaTeX)."""
    report_cfg = config.get("report", {}) if config else {}
    output_dir = Path(report_cfg.get("output_dir", "output/report"))
    output_dir.mkdir(parents=True, exist_ok=True)

    export_formats = report_cfg.get("formats", ["md"])

    generated = {}

    if "md" in export_formats or "markdown" in export_formats:
        md_path = export_markdown_report(solver_result, validation_result, viz_result,
                                         output_dir / "report.md")
        generated["markdown"] = md_path

    if "tex" in export_formats or "latex" in export_formats:
        tex_path = export_latex_report(solver_result, validation_result, viz_result,
                                       output_dir / "report.tex")
        generated["latex"] = tex_path

    return {
        "status": "report_generated",
        "files": generated,
        "output_dir": str(output_dir),
    }